### ISSUE TITLE
How to get the full path of previewed file?

### ISSUE THREAD

**Issue by praharshjain** [jtbandes/quicklookjs#2]
I was trying to use this with my electron app to enable quicklook preview support. Is there a way to get the full path of the file?
Also, is there a way to use an HTML page from my app (not copied to extension bundle) as the preview page?

**Comment by jtbandes** [comment]
I'm curious what you are hoping to do with the full path — is it just for display purposes? I am guessing you wouldn't really be able to do anything else with it on the page (since the web APIs don't allow JavaScript to access files by path).

For your 2nd question you might be able to [adjust `pagePath`](https://github.com/jtbandes/quicklookjs?tab=readme-ov-file#-configuration) using `../..` etc. so it points at the html file in your app bundle. I haven't tried this before but you could give it a shot.

**Comment by praharshjain** [comment]
I am working on an electron app capable of opening several file types - https://github.com/praharshjain/Vudit-Desktop

All of the viewers I have are JavaScript-based and require passing a full file path (and then do a fetch/Ajax, as Electron allows it even for a local file). I am planning to serve them on a custom port using Node and use that URL with file path as query param to preview a file.

Then, in preview.html, I will have to simply do a redirect using `window.location` (it works with `navigationComplete` as `loadingStrategy`). But I need the full file path in any case.

**Comment by jtbandes** [comment]
Making the full path accessible should definitely be possible – you could try to make it work and submit a PR if you are interested. But my instinct is that it's not the best solution to the problem...

> All of the viewers I have are JavaScript-based and require passing a full file path (and then do a fetch/Ajax, as Electron allows it even for a local file). I am planning to serve them on a custom port using Node and use that URL with file path as query param to preview a file.

How/when will you run the Node server? It doesn't seem ideal if your app has to be running a server in the background in order for the QL preview to work – the point of QL being implemented in an extension is that it can run while the main app is not running (and it's nice for the extension to be self-contained in a way that does not require network access).

I would think the `fetch()` is not really required for individual viewers — if possible to change the architecture, it would be nicer if they can operate on a Blob or Uint8Array directly. Then you would be able to pass in the File object (which inherits from Blob). For example, [this implementation](https://github.com/foxglove/studio/blob/038695cf27a90de1f2084203663d4de9cb21a1a9/packages/studio-desktop/src/quicklook/getIndexedMcapInfo.ts#L11) uses the `.size` and `.slice()` APIs on the File object to adapt it to some [reader code](https://mcap.dev/docs/typescript/classes/_mcap_core.McapIndexedReader) that is source-agnostic.

**Comment by praharshjain** [comment]
> It doesn't seem ideal if your app has to be running a server in the background in order for the QL preview to work – the point of QL being implemented in an extension is that it can run while the main app is not running (and it's nice for the extension to be self-contained in a way that does not require network access).

I agree with this, but I am trying to add QL support for multiple file types. Having all that logic in one HTML file is not easy to manage and will make things too complicated.
Thinking of alternate ways, is it possible to have support for different preview page paths for different types of files? Will you be considering this?

**Comment by jtbandes** [comment]
Would it work to check `file.name` and then update `window.location` to go to a different page based on the path extension?

**Comment by praharshjain** [comment]
If I use `window.location`, I will lose file contents. In this case full path is needed. Otherwise, if I can have different preview page paths for different file types, I can directly write the logic in those pages.

**Comment by jtbandes** [comment]
Calling `quicklook.getPreviewedFile()` again in the new page doesn’t work? (I never tested this but I imagine it _could_ maybe work)

**Comment by praharshjain** [comment]
Calling `quicklook.getPreviewedFile()` worked. I can now use redirect to different pages based on file type.

But I still need the full path in some cases (eg setting src for img, audio, or video element).
I can do a quick PR to add this. Can you please guide me on where to start (as I do not have much experience with Swift)?
Should it be a new function something like `getFilePath` or should I add the path to the object that gets returned from `getPreviewedFile`?

**Comment by jtbandes** [comment]
> Should it be a new function something like `getFilePath` or should I add the path to the object that gets returned from `getPreviewedFile`?

I think it might be best to change getPreviewedFile to return an object, like `{ file, path }` instead of just returning `file`.

The getPreviewedFile function is implemented here:

https://github.com/jtbandes/quicklookjs/blob/1baeff70ceb9aa880e3bb4fcae208a9a7586cbdd/PreviewExtension/PreviewViewController.swift#L115-L117

This invokes the `case .getPreviewedFile:` code which does some setup and runs `clickFileInput`:

https://github.com/jtbandes/quicklookjs/blob/1baeff70ceb9aa880e3bb4fcae208a9a7586cbdd/PreviewExtension/PreviewViewController.swift#L227

This triggers a click event which results in the runOpenPanel method being called:

https://github.com/jtbandes/quicklookjs/blob/1baeff70ceb9aa880e3bb4fcae208a9a7586cbdd/PreviewExtension/PreviewViewController.swift#L273-L276

I guess you will need to figure out how to pass this previewedFileURL back to JS. It might have to be independent from the File object since the WKWebView internally handles translating the `runOpenPanel` result into the File object.

**Comment by praharshjain** [comment]
@jtbandes I have raised a small PR - https://github.com/jtbandes/quicklookjs/pull/3
Please have a look.

**Comment by praharshjain** [comment]
Hi @jtbandes I have raised a small PR - https://github.com/jtbandes/quicklookjs/pull/3
Please have a look.
